package example.cars;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;


@DynamoDBTable(tableName = Car.BASE_TABLE_NAME)
@Data
public class Car {

  public static final String BASE_TABLE_NAME = "Cars";

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String carId;

  @DynamoDBAttribute
  private String name;

}
